# set base image (host OS)
FROM python:3.9

# set the working directory in the container
WORKDIR /app

COPY . /app

# install dependencies
RUN pip install Flask



# command to run on container star

CMD [ "python","src/AC2OOM.py" ]
